CREATE TYPE "ExpenseCategory" AS ENUM (
  'TRIP_ALLOWANCE',
  'DRIVER_SALARY',
  'FUEL',
  'TOLL_PARKING',
  'LOADING_UNLOADING',
  'REPAIR_MAINTENANCE',
  'SPAREPART',
  'OFFICE_OPERATIONAL',
  'OTHER'
);

ALTER TABLE "Expense"
ADD COLUMN "category" "ExpenseCategory" NOT NULL DEFAULT 'OTHER';
