ALTER TABLE "Customer"
ADD COLUMN "cargoLossTolerancePercent" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Invoice"
ADD COLUMN "ratePerKg" INTEGER,
ADD COLUMN "billableQuantity" DOUBLE PRECISION,
ADD COLUMN "tolerancePercent" DOUBLE PRECISION;

ALTER TABLE "SingleTripInvoiceLine"
ADD COLUMN "plannedWeightKg" DOUBLE PRECISION,
ADD COLUMN "billableWeightKg" DOUBLE PRECISION,
ADD COLUMN "cargoLossWeightKg" DOUBLE PRECISION,
ADD COLUMN "tolerancePercent" DOUBLE PRECISION;
