CREATE TYPE "TripPurpose" AS ENUM ('DELIVERY', 'EMPTY_RETURN');
ALTER TABLE "Trip" ALTER COLUMN "orderId" DROP NOT NULL;
ALTER TABLE "Trip" ADD COLUMN "purpose" "TripPurpose" NOT NULL DEFAULT 'DELIVERY';
ALTER TABLE "Trip" ADD COLUMN "operationalReason" TEXT;
