import { useEffect, useMemo, useState } from "react";
import { FiActivity, FiArrowDownLeft, FiArrowUpRight, FiBookOpen, FiCalendar, FiCheckCircle, FiCreditCard, FiDollarSign, FiRefreshCw, FiTrendingDown, FiTrendingUp } from "react-icons/fi";
import { api } from "../api";
import { useLiveRefresh } from "../liveUpdates";
import LoadingState from "../components/LoadingState";
import "./Accounting.css";
const money=value=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(value)||0);
const date=value=>new Date(value).toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"});
const start=()=>`${new Date().getFullYear()}-01-01`;
const labels={ASSET:"Aset",LIABILITY:"Liabilitas",EQUITY:"Ekuitas",REVENUE:"Pendapatan",EXPENSE:"Beban"};
export default function Accounting(){
 const [data,setData]=useState({summary:{},accounts:[],entries:[]}),[from,setFrom]=useState(start()),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[tab,setTab]=useState("journal"),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{setData(await api(`/accounting/overview?from=${from}&to=${to}`));}catch(err){setError(err.message);}finally{setLoading(false)}}
	 // Initial request only; later period changes are applied explicitly by the user.
	 // eslint-disable-next-line react-hooks/exhaustive-deps
	 useEffect(()=>{load()},[]);useLiveRefresh(load);
 async function sync(){setSyncing(true);setNotice("");setError("");try{const result=await api("/accounting/sync",{method:"POST"});await load();setNotice(`Sinkronisasi selesai. ${result.processed||0} transaksi diperiksa tanpa jurnal ganda.`);}catch(err){setError(err.message)}finally{setSyncing(false)}}
 const grouped=useMemo(()=>data.accounts.reduce((result,account)=>{(result[account.type]??=[]).push(account);return result},{}),[data.accounts]);
 const profit=Number(data.summary.profit||0);
 return <div className="acct-page">
  <header className="acct-hero"><div className="acct-hero-copy"><span>KEUANGAN · GENERAL LEDGER</span><h1>Accounting</h1><p>Ringkasan posisi keuangan dan jurnal otomatis dalam satu tampilan.</p></div><div className="acct-toolbar"><div className="acct-period-card"><FiCalendar/><label><small>DARI</small><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><i/><label><small>SAMPAI</small><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load} disabled={loading}>Terapkan</button></div><button className={`acct-sync ${syncing?"syncing":""}`} onClick={sync} disabled={loading||syncing}><FiRefreshCw className={syncing?"acct-spin":""}/>{syncing?"Menyinkronkan…":"Sinkronkan"}</button></div></header>
  {syncing&&<div className="acct-message progress"><span className="acct-progress-dot"/><div><strong>Sinkronisasi sedang berjalan</strong><small>Memeriksa invoice, pembayaran, pembelian, dan pengeluaran.</small></div></div>}{notice&&<div className="acct-message success"><FiCheckCircle/><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}{error&&<div className="acct-message error">{error}</div>}
  <section className="acct-overview"><Metric icon={<FiDollarSign/>} label="Kas & Bank" value={data.summary.cash} note="Saldo tersedia" tone="green"/><Metric icon={<FiArrowDownLeft/>} label="Piutang Usaha" value={data.summary.receivables} note="Belum diterima" tone="blue"/><Metric icon={<FiArrowUpRight/>} label="Utang Usaha" value={data.summary.payables} note="Belum dibayar" tone="amber"/><Metric icon={profit<0?<FiTrendingDown/>:<FiTrendingUp/>} label="Laba / Rugi" value={profit} note="Periode terpilih" tone={profit<0?"red":"solid"}/></section>
  <section className="acct-performance"><div className="acct-performance-title"><span><FiActivity/></span><div><small>KINERJA PERIODE</small><strong>Ringkasan laba rugi</strong></div></div><Performance label="Pendapatan" value={data.summary.revenue} icon={<FiTrendingUp/>}/><div className="acct-operator">−</div><Performance label="Total Beban" value={data.summary.expenses} icon={<FiTrendingDown/>}/><div className="acct-operator">=</div><Performance label="Laba Bersih" value={profit} emphasis negative={profit<0} icon={<FiBookOpen/>}/></section>
  <section className="acct-ledger"><div className="acct-ledger-head"><div><span>BUKU BESAR</span><h2>Catatan keuangan</h2><p>Periksa transaksi dan saldo akun pada periode yang dipilih.</p></div><nav className="acct-tabs"><button className={tab==="journal"?"active":""} onClick={()=>setTab("journal")}><FiBookOpen/>Jurnal Umum <b>{data.entries.length}</b></button><button className={tab==="accounts"?"active":""} onClick={()=>setTab("accounts")}><FiCreditCard/>Daftar Akun <b>{data.accounts.length}</b></button></nav></div><div className="acct-panel">{loading?<LoadingState label="Memuat accounting" note="Menyusun jurnal, saldo akun, dan laba rugi…" rows={6}/>:tab==="journal"?<Journal entries={data.entries}/>:<Accounts grouped={grouped}/>}</div></section>
 </div>
}
function Metric({icon,label,value,note,tone}){return <article className={`acct-metric ${tone}`}><span className="acct-metric-icon">{icon}</span><small>{label}</small><strong>{money(value)}</strong><em>{note}</em></article>}
function Performance({label,value,icon,emphasis,negative}){return <div className={`acct-performance-item ${emphasis?"emphasis":""} ${negative?"negative":""}`}><span>{icon}</span><small>{label}</small><strong>{money(value)}</strong></div>}
function Journal({entries}){if(!entries.length)return <Empty text="Belum ada jurnal pada periode ini."/>;return <div className="acct-table"><table><thead><tr><th>Tanggal</th><th>Nomor & sumber</th><th>Keterangan</th><th>Akun</th><th className="number">Debit</th><th className="number">Kredit</th></tr></thead><tbody>{entries.flatMap(entry=>entry.lines.map((line,index)=><tr key={line.id} className={index===0?"entry-start":"entry-line"}><td>{index===0?date(entry.date):""}</td><td>{index===0&&<div className="acct-reference"><b>{entry.number}</b><span>{entry.sourceType?.replaceAll("_"," ")||"MANUAL"}</span></div>}</td><td>{index===0?entry.description:""}</td><td><div className="acct-account"><b>{line.account.code}</b><span>{line.account.name}</span></div></td><td className={`number ${line.debit?"debit":""}`}>{line.debit?money(line.debit):"—"}</td><td className={`number ${line.credit?"credit":""}`}>{line.credit?money(line.credit):"—"}</td></tr>))}</tbody></table></div>}
function Accounts({grouped}){return <div className="acct-groups">{Object.entries(grouped).map(([type,accounts])=><article key={type}><header><div><span>{type.slice(0,2)}</span><h3>{labels[type]||type}</h3></div><b>{accounts.length} akun</b></header>{accounts.map(account=><div className="acct-account-row" key={account.id}><span><b>{account.code}</b>{account.name}</span><strong>{money(account.balance)}</strong></div>)}</article>)}</div>}
function Empty({text}){return <div className="acct-empty"><span><FiBookOpen/></span><strong>Belum ada data</strong><p>{text}</p></div>}
