import { useEffect, useMemo, useState } from "react";
import { FiBookOpen, FiCheckCircle, FiRefreshCw, FiTrendingDown, FiTrendingUp } from "react-icons/fi";
import { api } from "../api";
import { useLiveRefresh } from "../liveUpdates";
import "./Accounting.css";
import "./AccountingFeedback.css";
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const date=v=>new Date(v).toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"});
const start=()=>`${new Date().getFullYear()}-01-01`;
export default function Accounting(){
 const [data,setData]=useState({summary:{},accounts:[],entries:[]}); const [from,setFrom]=useState(start()); const [to,setTo]=useState(new Date().toISOString().slice(0,10)); const [tab,setTab]=useState("journal"); const [loading,setLoading]=useState(true); const [syncing,setSyncing]=useState(false); const [notice,setNotice]=useState(""); const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{setData(await api(`/accounting/overview?from=${from}&to=${to}`));}catch(e){setError(e.message);}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useLiveRefresh(load);
 async function sync(){setSyncing(true);setNotice("");setError("");try{const result=await api("/accounting/sync",{method:"POST"});await load();setNotice(`Sinkronisasi selesai. ${result.processed||0} transaksi diperiksa tanpa membuat jurnal ganda.`);}catch(e){setError(e.message);}finally{setSyncing(false)}}
 const grouped=useMemo(()=>Object.groupBy?Object.groupBy(data.accounts,x=>x.type):data.accounts.reduce((a,x)=>((a[x.type]??=[]).push(x),a),{}),[data.accounts]);
 return <div className="acct-page"><header className="acct-head"><div><span>GENERAL LEDGER</span><h1>Accounting</h1><p>Jurnal otomatis dari seluruh penerimaan dan penggunaan uang.</p></div><div className="acct-head-actions"><button className={`secondary ${syncing?"syncing":""}`} onClick={sync} disabled={loading||syncing} aria-busy={syncing}><FiRefreshCw className={syncing?"acct-spin":""}/> {syncing?"Sedang menyinkronkan…":"Sinkronkan Transaksi"}</button></div></header>
 <div className="acct-period"><label>Dari<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Sampai<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load}>Terapkan</button></div>
 {syncing&&<div className="acct-sync-progress"><span className="acct-progress-dot"/><div><strong>Sinkronisasi sedang berjalan</strong><small>Memeriksa invoice, pembayaran pelanggan, pembelian, dan pengeluaran…</small></div></div>}{notice&&<div className="acct-success"><FiCheckCircle/><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}{error&&<div className="acct-error">{error}</div>}
 <section className="acct-stats"><article><small>Kas & Bank</small><strong>{money(data.summary.cash)}</strong><span>Saldo periode berjalan</span></article><article><small>Piutang Usaha</small><strong>{money(data.summary.receivables)}</strong><span>Belum diterima</span></article><article><small>Utang Usaha</small><strong>{money(data.summary.payables)}</strong><span>Belum dibayar</span></article><article className={(data.summary.profit||0)<0?"loss":"profit"}><small>Laba / Rugi</small><strong>{money(data.summary.profit)}</strong><span>Pendapatan dikurangi beban</span></article></section>
 <section className="acct-profit"><div><FiTrendingUp/><span>Pendapatan</span><strong>{money(data.summary.revenue)}</strong></div><div><FiTrendingDown/><span>Beban</span><strong>{money(data.summary.expenses)}</strong></div><div className="net"><FiBookOpen/><span>Laba Bersih</span><strong>{money(data.summary.profit)}</strong></div></section>
 <nav className="acct-tabs"><button className={tab==="journal"?"active":""} onClick={()=>setTab("journal")}>Jurnal Umum</button><button className={tab==="accounts"?"active":""} onClick={()=>setTab("accounts")}>Daftar Akun & Saldo</button></nav>
 <section className="acct-panel">{tab==="journal"?<div className="acct-table"><table><thead><tr><th>Tanggal</th><th>Nomor</th><th>Keterangan</th><th>Sumber</th><th>Akun</th><th>Debit</th><th>Kredit</th></tr></thead><tbody>{data.entries.flatMap(entry=>entry.lines.map((line,index)=><tr key={line.id}><td>{index===0?date(entry.date):""}</td><td>{index===0?<b>{entry.number}</b>:""}</td><td>{index===0?entry.description:""}</td><td>{index===0?<span className="acct-source">{entry.sourceType?.replaceAll("_"," ")||"MANUAL"}</span>:""}</td><td>{line.account.code} · {line.account.name}</td><td>{line.debit?money(line.debit):"—"}</td><td>{line.credit?money(line.credit):"—"}</td></tr>))}</tbody></table>{!loading&&!data.entries.length&&<Empty text="Belum ada jurnal pada periode ini."/>}</div>:<div className="acct-groups">{Object.entries(grouped).map(([type,accounts])=><article key={type}><h3>{({ASSET:"Aset",LIABILITY:"Liabilitas",EQUITY:"Ekuitas",REVENUE:"Pendapatan",EXPENSE:"Beban"})[type]}</h3>{accounts.map(account=><div key={account.id}><span><b>{account.code}</b> {account.name}</span><strong>{money(account.balance)}</strong></div>)}</article>)}</div>}</section></div>
}
function Empty({text}){return <div className="acct-empty"><FiBookOpen/><p>{text}</p></div>}
