ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'REMAINING_TRIP_ALLOWANCE';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'UNLOADING_FEE';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'FUEL_LOAN';
