ALTER TABLE "Trip"
ADD COLUMN "sackCount" INTEGER,
ADD COLUMN "kgPerSack" DOUBLE PRECISION,
ADD COLUMN "plannedWeightKg" DOUBLE PRECISION;

ALTER TABLE "TripOrderAllocation"
ADD COLUMN "sackCount" INTEGER,
ADD COLUMN "kgPerSack" DOUBLE PRECISION,
ADD COLUMN "plannedWeightKg" DOUBLE PRECISION;
