CREATE TYPE "TripPhase" AS ENUM ('PLANNED', 'TO_PICKUP', 'AT_PICKUP', 'TO_DESTINATION', 'AT_DESTINATION', 'COMPLETED');

ALTER TABLE "Trip"
ADD COLUMN "phase" "TripPhase" NOT NULL DEFAULT 'PLANNED',
ADD COLUMN "pickupLat" DOUBLE PRECISION,
ADD COLUMN "pickupLng" DOUBLE PRECISION,
ADD COLUMN "pickupRadiusM" INTEGER NOT NULL DEFAULT 400,
ADD COLUMN "pickupArrivedAt" TIMESTAMP(3),
ADD COLUMN "loadedAt" TIMESTAMP(3);

UPDATE "Trip"
SET "phase" = CASE
  WHEN "status" = 'COMPLETED' THEN 'COMPLETED'::"TripPhase"
  WHEN "status" = 'ARRIVED' THEN 'AT_DESTINATION'::"TripPhase"
  WHEN "status" = 'DISPATCHED' THEN 'TO_DESTINATION'::"TripPhase"
  ELSE 'PLANNED'::"TripPhase"
END;
